/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X6AlDGeU4Jx
 */
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export default function HomeComponent() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <div>
            
            {/* <Image
              src="https://dashboard.daryan.com.mx/assets/img/logo.png"
              width={500}
              height={500}
              alt="Picture of the author"
            /> */}
          </div>
          <span className="mx-4 font-semibold text-xl">Daryan</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="/services">
            Services
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Testimonials
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1
                  className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                  Ensuring Quality, Ensuring Success
                </h1>
                <p
                  className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  We provide comprehensive quality inspection services to ensure your products meet the highest
                  standards.
                </p>
              </div>
              <div className="space-x-4">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#">
                  Learn more
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-center">Our Inspection Services</h2>
            <div
              className="grid items-center gap-6 lg:grid-cols-3 lg:gap-12 xl:grid-cols-3 my-10">
              <Card>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold">Product Inspection</h3>
                  <p className="text-gray-500 mt-2">
                    We inspect your products to ensure they meet the required quality standards.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold">Process Inspection</h3>
                  <p className="text-gray-500 mt-2">
                    We assess your production processes to identify areas of improvement.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold">Pre-shipment Inspection</h3>
                  <p className="text-gray-500 mt-2">
                    We conduct thorough checks before shipment to ensure product quality.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2
              className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-center">
              Client Testimonials
            </h2>
            <div
              className="grid items-center gap-6 lg:grid-cols-3 lg:gap-12 xl:grid-cols-3 my-10">
              <Card>
                <CardContent className="p-4">
                  <p className="text-gray-500 mt-2">
                    "Quality Inspection Inc has helped us improve our product quality significantly. Their team is
                    professional and thorough."
                  </p>
                  <div className="flex items-center mt-4">
                    <Avatar alt="Client Avatar" src="/placeholder.svg?height=32&width=32" />
                    <div className="ml-2">
                      <p className="text-sm font-bold">John Doe</p>
                      <p className="text-xs text-gray-500">CEO, Company A</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <p className="text-gray-500 mt-2">
                    "Their inspection services are excellent. They have helped us identify and rectify quality issues
                    early."
                  </p>
                  <div className="flex items-center mt-4">
                    <Avatar alt="Client Avatar" src="/placeholder.svg?height=32&width=32" />
                    <div className="ml-2">
                      <p className="text-sm font-bold">Jane Smith</p>
                      <p className="text-xs text-gray-500">Product Manager, Company B</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <p className="text-gray-500 mt-2">
                    "I highly recommend Quality Inspection Inc. They have significantly improved our product outcomes
                    and customer satisfaction."
                  </p>
                  <div className="flex items-center mt-4">
                    <Avatar alt="Client Avatar" src="/placeholder.svg?height=32&width=32" />
                    <div className="ml-2">
                      <p className="text-sm font-bold">Robert Johnson</p>
                      <p className="text-xs text-gray-500">CTO, Company C</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <h2
              className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-center">Contact Us</h2>
            <div className="mx-auto w-full max-w-md mt-10">
              <form className="grid gap-4">
                <Input className="px-4 py-2" placeholder="Your Name" type="text" />
                <Input className="px-4 py-2" placeholder="Your Email" type="email" />
                <Input className="px-4 py-2" placeholder="Subject" type="text" />
                <textarea className="px-4 py-2 h-24" placeholder="Your Message" />
                <Button className="bg-gray-900 text-white px-4 py-2" type="submit">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© Quality Inspection Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>)
  );
}
